% Program Code for Task 1 and Task 2
clear all
load = [22 22 18 15 18 20 29 41 46 72 75 92 81 94 90 97 80 74 60 67 75 66 29 28];
wind = [31 32 43 48 47 36 6 8 12 18 26 39 45 45 50 46 41 44 41 50 49 31 31 50];

% Without storage, it is economical to use all the energy generated by the
% wind used in supplying load and the remaining load is catered by the
% diesel generator
en_wo_sto = 0;
for i=1:24
    if(wind(i) >= load(i))
        en_wo_sto = en_wo_sto + load(i);
    else
        en_wo_sto = en_wo_sto + wind(i);
    end
end
disp(['Maximum renewable energy without storage is ',num2str(en_wo_sto)]);

% If we have sufficient energy, the entire wind production will used
% to supply the load throughtout the day as load is greater than the energy
% produced by the wind
disp(['Maximum renewable energy with storage is ',num2str(sum(wind))]);

% Fuel used by the diesel generator to supply load on its own
diesel_startup = 1;
diesel_inc = 0.25;
diesel_noload = 3;
fuel_used_do = sum(load*0.25) + diesel_noload*24 + diesel_startup;
disp(['Fuel used by the diesel generator ',num2str(fuel_used_do)]);

diesel_start = 0;
diesel_stop = 1;
stored_energy = 0;
fuel_used = 0;
for i=1:24
    if(wind(i) >= load(i))
        stored_energy = stored_energy + (wind(i) - load(i));
        if(diesel_stop == 0)
            diesel_stop = 1;
        end
    elseif ((wind(i) +stored_energy) >= load(i))
            stored_energy = stored_energy - (load(i) - wind(i));
            if(diesel_stop == 0)
                diesel_stop = 1;
            end
    else
        if ((wind(i) +stored_energy) < load(i))
            if(diesel_stop==1)
                diesel_start = diesel_start + 1;
                diesel_stop = 0;
            end
            fuel_used = fuel_used + (load(i) - wind(i) - stored_energy)*0.25 + 3;
            stored_energy = 0;
        end
    end
end
fuel_used = fuel_used + diesel_start;
disp(['Fuel used with hybrid system is ',num2str(fuel_used),' liters']);
disp(['Maximum fuel saved is ',num2str(fuel_used_do - fuel_used)]);